#include "particle_design.h"
#include "particle_model.h"
#include <cmath>
#include <fstream>
#include <iostream>
#include <limits>
#include <sstream>
#include <string>
#include <vector>
namespace {
int failures=0;
void expect(bool c,const std::string& m){if(!c){++failures;std::cerr<<"FAIL: "<<m<<'\n';}}
bool near(float a,float b,float t=0.0005f){return std::isfinite(a)&&std::isfinite(b)&&std::fabs(a-b)<=t;}
void expectNear(float a,float b,const std::string& m,float t=0.0005f){if(!near(a,b,t)){++failures;std::cerr<<"FAIL: "<<m<<" actual="<<a<<" expected="<<b<<" tolerance="<<t<<'\n';}}
particles::Design known(){return {0.01f,0.25f,8,0.02f,100,0.05f,1.0f,{0,0},2,1,4,10,{245,245,240},{10,80,160},{220,70,40}};}
particles::Particle particle(particles::Vec2 p,particles::Vec2 v,float age=0,float life=10){particles::Particle result(p,v,life);result.age=age;return result;}
struct Row{std::string name;float dt,x,vx,age;};
std::vector<Row> fixture(const char* path){std::ifstream in(path);expect(in.good(),"oracle opens");std::vector<Row> rows;std::string line;while(std::getline(in,line)){if(line.empty()||line[0]=='#')continue;Row r{};std::string extra;std::istringstream f(line);bool parsed=static_cast<bool>(f>>r.name>>r.dt>>r.x>>r.vx>>r.age);bool exact=parsed&&!(f>>extra);expect(exact,"oracle row has exactly five fields");if(exact)rows.push_back(r);}return rows;}
void oracleCases(const std::vector<Row>& rows){expect(rows.size()==2,"oracle has two rows");auto d=known();d.fixed_step=.25f;d.maximum_frame_time=.25f;d.spawn_interval=.25f;d.lifetime=10;particles::Particle p=particle({10,20},{10,0});for(const auto&r:rows){particles::updateParticle(p,r.dt,d,{100,100});expectNear(p.position.x,r.x,r.name+" x");expectNear(p.velocity.x,r.vx,r.name+" vx");expectNear(p.age,r.age,r.name+" age");}}
void dragCases(){expectNear(particles::dragMultiplier(1,.25f),0.7788008f,"known exponential drag");expectNear(particles::dragMultiplier(1,.5f),particles::dragMultiplier(1,.25f)*particles::dragMultiplier(1,.25f),"drag partitions multiplicatively");expectNear(particles::dragMultiplier(-1,.1f),1,"invalid drag is identity");}
void cadencePartitionCases(){auto d=known();d.lifetime=5;particles::Emitter once,split;particles::reset(once,{50,50},17);particles::reset(split,{50,50},17);auto a=particles::advanceFrame(once,.08f,d,{100,100});auto b1=particles::advanceFrame(split,.03f,d,{100,100});auto b2=particles::advanceFrame(split,.05f,d,{100,100});expect(a.spawned==4&&b1.spawned+b2.spawned==4,"spawn cadence counts exact fixed steps");expect(once.total_spawned==split.total_spawned&&once.particles.size()==split.particles.size(),"frame partition preserves counts");for(std::size_t i=0;i<once.particles.size();++i){expectNear(once.particles[i].position.x,split.particles[i].position.x,"partition x");expectNear(once.particles[i].position.y,split.particles[i].position.y,"partition y");expectNear(once.particles[i].age,split.particles[i].age,"partition age");}}
void capPauseAndInvalidCases(){auto d=known();d.maximum_catch_up_steps=3;particles::Emitter e;particles::reset(e,{50,50},2);auto r=particles::advanceFrame(e,1.0f,d,{100,100});expect(r.simulated_steps==3,"catch-up work capped");expectNear(r.dropped_time,.97f,"frame clamp plus excess fixed steps explicitly dropped",.001f);expect(e.accumulator<d.fixed_step,"only substep remainder retained");particles::setPaused(e,true);auto paused=particles::advanceFrame(e,100,d,{100,100});expect(paused.simulated_steps==0&&near(e.accumulator,0),"paused spike accrues no backlog");particles::setPaused(e,false);auto resumed=particles::advanceFrame(e,.01f,d,{100,100});expect(resumed.simulated_steps==1,"resume simulates only new time");auto before=e;auto nan=particles::advanceFrame(e,std::numeric_limits<float>::quiet_NaN(),d,{100,100});expect(nan.simulated_steps==0&&e.total_spawned==before.total_spawned,"non-finite frame rejected transactionally");auto tiny=particles::advanceFrame(e,.02f,d,{3,100});expect(tiny.simulated_steps==0&&e.total_spawned==before.total_spawned,"tiny bounds rejected transactionally");}
void expiryRemovalCases(){std::vector<particles::Particle> ps{particle({10,10},{0,0},.049f,.05f),particle({20,20},{0,0},.05f,.05f),particle({30,30},{0,0},.06f,.05f),particle({40,40},{0,0},.01f,.05f)};particles::removeExpired(ps);expect(ps.size()==2,"simultaneous expired objects removed safely");expect(near(ps[0].position.x,10)&&near(ps[1].position.x,40),"remove_if preserves survivor order");ps[0].age=ps[0].lifetime;particles::removeExpired(ps);expect(ps.size()==1&&near(ps[0].position.x,40),"age equal lifetime expires");}
void boundaryCases(){auto d=known();d.drag_rate=0;d.acceleration={0,0};const particles::Bounds b{100,80};auto check=[&](particles::Particle p,const std::string& name,bool horizontal,bool positive){particles::updateParticle(p,.1f,d,b);expect(p.position.x>=2&&p.position.x<=98&&p.position.y>=2&&p.position.y<=78,name+" clamped inside");float v=horizontal?p.velocity.x:p.velocity.y;expect(positive?v>0:v<0,name+" reflected inward");};check(particle({2.1f,40},{-10,0}),"left",true,true);check(particle({97.9f,40},{10,0}),"right",true,false);check(particle({50,2.1f},{0,-10}),"top",false,true);check(particle({50,77.9f},{0,10}),"bottom",false,false);}
void historyCases(){auto d=known();d.drag_rate=0;d.maximum_history=3;auto p=particle({10,10},{10,0});for(int i=0;i<5;++i)particles::updateParticle(p,.1f,d,{100,100});expect(p.history.size()==3,"trail history capped");expectNear(p.history[0].x,13,"oldest retained trail point ordered");expectNear(p.history[2].x,15,"newest trail point ordered");}
void deterministicCases(){auto d=known();d.lifetime=5;particles::Emitter a,b,c;particles::reset(a,{50,50},123);particles::reset(b,{50,50},123);particles::reset(c,{50,50},124);for(int i=0;i<10;++i){particles::advanceFrame(a,.02f,d,{100,100});particles::advanceFrame(b,.02f,d,{100,100});particles::advanceFrame(c,.02f,d,{100,100});}expect(a.particles.size()==b.particles.size(),"same seed replay count");for(std::size_t i=0;i<a.particles.size();++i){expectNear(a.particles[i].position.x,b.particles[i].position.x,"same seed x");expectNear(a.particles[i].position.y,b.particles[i].position.y,"same seed y");}expect(!near(a.particles.front().velocity.x,c.particles.front().velocity.x)||!near(a.particles.front().velocity.y,c.particles.front().velocity.y),"different seed varies launch");particles::Emitter zero,former_sentinel;particles::reset(zero,{50,50},0u);particles::reset(former_sentinel,{50,50},0x6d2b79f5u);particles::advanceFrame(zero,.02f,d,{100,100});particles::advanceFrame(former_sentinel,.02f,d,{100,100});expect(zero.random_state!=former_sentinel.random_state,"zero and former sentinel retain distinct generator states");expect(!near(zero.particles.front().velocity.x,former_sentinel.particles.front().velocity.x)||!near(zero.particles.front().velocity.y,former_sentinel.particles.front().velocity.y),"zero and former sentinel produce distinct launches");expect(particles::finiteState(a,d,{100,100}),"replay state finite and stroke-aware bounded");}
void constructorCases(){particles::Particle p({12,14},{3,4},2.5f);expectNear(p.age,0,"constructor starts age at zero");expectNear(p.lifetime,2.5f,"constructor stores lifetime");expect(p.history.size()==1,"constructor starts one-point history");expectNear(p.history.front().x,12,"constructor history starts at position x");expectNear(p.history.front().y,14,"constructor history starts at position y");}
void originAndExactBoundsCases(){auto d=known();const particles::Bounds b{100,80};expect(particles::originInBounds({2,2},b,2),"top-left legal origin edge included");expect(particles::originInBounds({98,78},b,2),"bottom-right legal origin edge included");expect(!particles::originInBounds({1,40},b,2),"origin outside left rejected");expect(!particles::originInBounds({99,40},b,2),"origin outside right rejected");expect(!particles::originInBounds({50,1},b,2),"origin outside top rejected");expect(!particles::originInBounds({50,79},b,2),"origin outside bottom rejected");const particles::Vec2 outside[]={{1,40},{99,40},{50,1},{50,79}};for(const auto origin:outside){particles::Emitter e;particles::reset(e,origin,7);e.accumulator=.005f;const auto before=e;const auto result=particles::advanceFrame(e,.02f,d,b);expect(result.simulated_steps==0&&result.spawned==0,"off-bound origin rejects frame");expectNear(e.accumulator,before.accumulator,"off-bound rejection preserves accumulator");expect(e.total_spawned==before.total_spawned&&e.particles.size()==before.particles.size(),"off-bound rejection preserves particle state");expect(!particles::finiteState(e,d,b),"finiteState rejects off-bound origin");}const particles::Bounds exact{4,4};expect(particles::boundsAreUsable(exact,2),"exact-diameter bounds are usable");expect(particles::originInBounds({2,2},exact,2),"exact-diameter bounds have one legal origin");particles::Emitter exact_emitter;particles::reset(exact_emitter,{2,2},8);expect(particles::finiteState(exact_emitter,d,exact),"exact-diameter empty state is finite");}
void capacityAndDropCases(){auto d=known();d.maximum_particles=2;d.lifetime=5;particles::Emitter capacity;particles::reset(capacity,{50,50},12);const auto spawned=particles::advanceFrame(capacity,.06f,d,{100,100});expect(capacity.particles.size()==2,"maximum_particles caps live particles");expect(capacity.total_spawned==2&&spawned.spawned==2,"capacity suppresses rather than counts extra spawns");auto capped=known();capped.maximum_catch_up_steps=3;particles::Emitter drops;particles::reset(drops,{50,50},3);const auto first=particles::advanceFrame(drops,1.0f,capped,{100,100});const auto second=particles::advanceFrame(drops,1.0f,capped,{100,100});expectNear(first.dropped_time,.97f,"first frame reports dropped time",.001f);expectNear(second.dropped_time,.97f,"second frame reports dropped time",.001f);expectNear(drops.dropped_time,1.94f,"emitter accumulates dropped time",.002f);}
void resetCases(){auto d=known();d.lifetime=5;particles::Emitter e;particles::reset(e,{50,50},41);particles::advanceFrame(e,.025f,d,{100,100});particles::setPaused(e,true);e.dropped_time=4.0f;particles::reset(e,{40,45},99);expect(e.particles.empty(),"reset clears particles");expectNear(e.accumulator,0,"reset clears accumulator");expectNear(e.spawn_clock,0,"reset clears spawn clock");expectNear(e.dropped_time,0,"reset clears dropped time");expect(!e.paused,"reset clears pause");expect(e.total_spawned==0,"reset clears spawn count");expectNear(e.origin.x,40,"reset stores origin x");expectNear(e.origin.y,45,"reset stores origin y");particles::Emitter replay;particles::reset(replay,{40,45},99);particles::advanceFrame(e,.02f,d,{100,100});particles::advanceFrame(replay,.02f,d,{100,100});expect(e.particles.size()==1&&replay.particles.size()==1,"reset replay spawns identically");expectNear(e.particles[0].velocity.x,replay.particles[0].velocity.x,"reset restores seeded velocity x");expectNear(e.particles[0].velocity.y,replay.particles[0].velocity.y,"reset restores seeded velocity y");}
void overflowAndContractCases(){auto d=known();d.drag_rate=0;const float extreme=std::numeric_limits<float>::max();auto p=particle({50,50},{extreme,0});const auto p_before=p;particles::updateParticle(p,extreme,d,{100,100});expect(p.position.x==p_before.position.x&&p.velocity.x==p_before.velocity.x&&p.age==p_before.age&&p.history.size()==p_before.history.size(),"overflowing acceleration/integration leaves particle unchanged");auto old=particle({50,50},{0,0},extreme,extreme);const auto old_before=old;particles::updateParticle(old,extreme,d,{100,100});expect(old.age==old_before.age&&old.position.x==old_before.position.x&&old.history.size()==old_before.history.size(),"overflowing age calculation leaves particle unchanged");particles::Emitter drop;particles::reset(drop,{50,50},13);drop.accumulator=.005f;drop.spawn_clock=.005f;drop.dropped_time=extreme;const auto drop_before=drop;const auto rejected=particles::advanceFrame(drop,extreme,d,{100,100});expect(rejected.simulated_steps==0&&rejected.dropped_time==0,"overflowing dropped-time total rejects frame");expect(drop.accumulator==drop_before.accumulator&&drop.spawn_clock==drop_before.spawn_clock&&drop.dropped_time==drop_before.dropped_time&&drop.total_spawned==drop_before.total_spawned&&drop.particles.size()==drop_before.particles.size(),"dropped-time overflow rejection is transactional");auto learner=makeParticleDesign();expect(particles::designIsValid(learner),"learner design valid");expect(learner.maximum_history>=4&&learner.young_color.r!=learner.old_color.r,"learner owns bounded trail and age palette");expect(!particles::boundsAreUsable({5,100},3),"tiny width rejected before inverted bounds");}
}
int main(int argc,char**argv){expect(argc==2,"usage supplies particle oracle");if(argc==2)oracleCases(fixture(argv[1]));constructorCases();dragCases();cadencePartitionCases();capPauseAndInvalidCases();expiryRemovalCases();boundaryCases();historyCases();deterministicCases();originAndExactBoundsCases();capacityAndDropCases();resetCases();overflowAndContractCases();if(failures){std::cerr<<"particle_model_test: "<<failures<<" failure(s)\n";return 1;}std::cout<<"particle_model_test: parsed oracle, constructor invariants, cadence/capacity/partition, capped accumulated drop, pause/reset/replay, expiry/removal, exponential drag, radius-aware origins and exact bounds, all boundaries, bounded ordered trails, deterministic full-state seeds without zero alias, transactional finite extremes, and learner contract passed\n";}
